### ISSUE TITLE
Support for symmetric matrices?

### ISSUE THREAD

**Issue by dpo** [kshyatt/CUSPARSE.jl#15]
I'm wondering if support for symmetric/hermitian matrices is in the cards as far as `csrmv` is concerned, and what the difficulties would be, if any.

Thanks for implementing this interface!

**Comment by kshyatt** [comment]
@dpo looking at the [csrmv](http://docs.nvidia.com/cuda/cusparse/#cusparse-lt-t-gt-csrmv) docs, telling CUSPARSE the matrix is symmetric or Hermitian should work. I think right now I default the flag to `CUSPARSE_MATRIX_TYPE_GENERAL`, but I could easily do the same thing `Base` does with `Symmetric` and `Hermitian` tags :)

**Comment by kshyatt** [comment]
@dpo Does the stuff I've added since you opened this issue address your needs?

**Comment by kshyatt** [comment]
As far as I can tell this functionality works now, feel free to reopen if that's not the case.

**Comment by dpo** [comment]
Sorry for the lack of activity. Many thanks for moving the package forward. I should be able to get to it in the near future.

**Comment by kshyatt** [comment]
I'm the one who ought to apologize! I'm very happy people are trying it
out. I'd love to hear about anything else you think could be improved.
