### ISSUE TITLE
CUSPARSE 0.4.0 fails Pkg.test("CUSPARSE")

### ISSUE THREAD

**Issue by denizyuret** [kshyatt/CUSPARSE.jl#18]
Here is the error message:

```
ERROR: LoadError: LoadError: UndefVarError: SparseArrays not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/nlg-05/dy_052/.julia/v0.4/CUSPARSE/src/CUSPARSE.jl, in expression starting on line 2
while loading /auto/nlg-05/dy_052/julia/pkg/v0.4/CUSPARSE/test/runtests.jl, in expression starting on line 1
```

**Comment by kshyatt** [comment]
Thanks for catching this! I'll take a look tonight - I was testing on `0.5-dev` and that might be the cause.

**Comment by kshyatt** [comment]
~~@denizyuret what version of Julia are you on? I'm on `0.4.3-pre+10` and tests pass locally.~~

Nevermind, I forgot to checkout. Fix incoming!

**Comment by kshyatt** [comment]
Ok, I've updated master - is this working for you now?

**Comment by denizyuret** [comment]
Yes, it passes now, thank you.  I was using 0.4.2 which is the current
default version at http://julialang.org/downloads.

deniz
