### ISSUE TITLE
Can't find / use csrmv

### ISSUE THREAD

**Issue by MichaelOhlrogge** [kshyatt/CUSPARSE.jl#19]
I notice that the csrmv function is mentioned in the "Working with CUSPARSE.jl" section of the readme file and is also listed as one of the functions supported.  When I load the package, however, and try ?CUSPARSE.csrmv, or try to use the function, I get the error:
ERROR: "csrmv" is not defined in module CUSPARSE  (I am able to reproduce the example with CUSPARSE.geam() just fine).

It looks like there is a CUSPARSE.mv function defined in the source code (I couldn't find csrmv explicitly defined in those either), but I couldn't seem to make it work right, although that could be just because I didn't correctly decipher the correct form of the inputs from the source code on that function.  I also saw versions such as cusparseDbsrmv mentioned, though I couldn't find how to operate those either, and a ?CUSPARSE.Dbsrmv call in the interpreter, for instance, yielded another not defined message.

**Comment by kshyatt** [comment]
Sorry - I've been super busy recently. I need to update the docs. Thank you for reminding me to do so!

**Comment by MichaelOhlrogge** [comment]
Great, that would be awesome!  It looks like a fantastic package and I'm eager to start checking it out.

**Comment by kshyatt** [comment]
I'm _finally_ (sorry) fixing this today! If you need to see an argument list, the `tests/` dir is a good place to start, or enter help mode in the REPL (with `?`) and try `CUSPARSE.mv`.

**Comment by kshyatt** [comment]
I'm now going to close this, since I've updated `README.md`. I need to add documentation for most of these functions so at least in help mode you'll get some more useful/less verbose output.

**Comment by MichaelOhlrogge** [comment]
Great, thanks!  I'm looking forward to checking this out again soon!

**Comment by MichaelOhlrogge** [comment]
Yes, wow, finally got to using this with some real Data.  It really zips!

**Comment by kshyatt** [comment]
Hooray! I'm glad it's working for you :)
