### ISSUE TITLE
Cannot find Visual Studio Installation (Windows 7)

### ISSUE THREAD

**Issue by bscohen1** [kshyatt/CUSPARSE.jl#28]
I am a bit of Julia newb, but when trying to install CUSPARSE.jl I am getting the following error:

LoadError: Cannot find proper Visual Studio installation. VS 2013, 2012, or 2010 is required....

I am using VS 2015 so perhaps this is an issue?

**Comment by kshyatt** [comment]
Hello,

Could you paste the full output of `Pkg.add`? That would be very helpful!

**Comment by bscohen1** [comment]
So Pkg.add("CUSPARSE") does not return an error (only "nothing to be done")

However, after typing "Pkg.update()" and then "using CUSPARSE" returns

ERROR: LoadError: LoadError: Cannot find libwrapcuda in error at error.jl:21
while loading C:\ ... \libcudart-6.5.jl, in expression starting on line 53
while loading C:\ ... \CUDArt.jl, in expression starting on line 27
ERROR: LoadError: Failed to precompile CUDArt to C:\....\CUDArt.jl in error at error.jl: 27
while loading C:\ ... \CUSPARSE.jl, in expression starting on line 9

Typing "using CUDArt" also gives me a similar message ...

**Comment by bscohen1** [comment]
Resolved this issues with #48.
