### ISSUE TITLE
Can you construct sparse matrices on the GPU

### ISSUE THREAD

**Issue by ranjanan** [kshyatt/CUSPARSE.jl#3]
Hey, I am working on an application where there a lot of time is spent _constructing_ sparse matrices. I was wondering if the sparse() implementation here is any faster than the normal sparse uses single threaded execution on CPU. (Forgive me if this is a newbie question)

Thanks a bunch,
Ranjan

**Comment by kshyatt** [comment]
Somehow I didn't get notified about this issue! Bad Github, BAD.

The sparse "constructors" in `CUSPARSE.jl` are set up to take full `I,J,V` arrays and assign them to a COO matrix. If you're trying to insert element-by-element, like having two loops that go `A[i,j] = v` then this will be very slow on the CPU and not possible on the GPU. When I construct a sparse matrix on the CPU or GPU I fill the three arrays first then assign them to the sparse "container". If you are already doing that then the GPU will not help you unless you can write a custom CUDA kernel to generate the `(i,j), v` tuples faster (`CUSPARSE.jl` doesn't provide this functionality). `CUSPARSE.jl` will only be faster at doing the matrix/vector or matrix/matrix ops, not constructing the matrix itself.

Does that answer your question?

**Comment by ranjanan** [comment]
Yes, thanks @kshyatt.
